### ISSUE TITLE
Exclude NFS server mounted

### ISSUE THREAD

**Issue by juandp77** [lzkelley/bkup_rpimage#11]
Hello,  Is there a way to exclude a nfs share mounted on /mnt by /etc/fstab on boot?

**Comment by dolorosus** [comment]
Stay tuned, I will create a pull request with some excludes.

**Comment by lzkelley** [comment]
@dolorosus there are no open PR's that I can see

**Comment by dolorosus** [comment]
Sorry my fault, The PR is now created.

**Comment by lzkelley** [comment]
Awesome, thanks @dolorosus, PR is merged.  @juandp77 I'm closing the issue, but please write back if you still have any problems.
