### ISSUE TITLE
Compact (not compress) resulting image file

### ISSUE THREAD

**Issue by ephestione** [lzkelley/bkup_rpimage#13]
Using this great tool to clone a system which boots from USB (no SD on the raspi), the backup runs OK but since it's a 16GB pendrive where 40MB boot partition and 4ishGB root partition are, I would expect 4GBish images, rather it creates 15gbish images.
I understand as it created an image "the apparent size of $SDCARD", is there a way to allocate only the real part1+part2 size instead? Or should I necessarily specify the image size with -s? This second option should work, but it statically allocates the destination image on the secondary pendrive making the process reeeaaaaal slow

**Comment by ephestione** [comment]
I realized that the static image size creation doesn't take that long of a time, I had a wrong impression, just tested it and it didn't seem to alter the final backup time.

**Comment by lzkelley** [comment]
I'm glad your solution worked out.  Thanks for updating the post!
