### ISSUE TITLE
It is backing up itself !

### ISSUE THREAD

**Issue by sasagr** [lzkelley/bkup_rpimage#18]
I have this problem. My external drive (for backup and other stuff) is mounted at boot in fstab and shared with smb. The location for the mount in mnt/usbsd.
When I start the backup I see that it back up also mnt/usbsd, where there is already the .img file.
So it makes a back up of itself??
Is there something I can do to avoid it?
or maybe add a function to skip "itself" back up?

**Comment by sasagr** [comment]
the problem was on the way the ext disk was mounted

**Comment by lazerdave** [comment]
What was the issue with the way your ext disk was mounted?  I'm having the same issue.  Thx.
