### ISSUE TITLE
image does not boot on recent Raspbian versions (using PARTUUIDs)

### ISSUE THREAD

**Issue by kobbejager** [lzkelley/bkup_rpimage#6]
Recent Rasbian versions use PARTUUIDs. 
When creating an image with this tool, the image and the partitions within it get a new PARTUUID. These are different from those defined in /etc/fstab and /boot/cmdline.txt. If you write the image as such on a new sdcard, this card won't boot.

Solution: change the PARTUUIDs manually in the above files in the image.

notes: 

- rpi-clone (https://github.com/billw2/rpi-clone) alters those files automatically. The main branch, however, does not allow to create images. This fork/branch (https://github.com/SeeSpotRun/rpi-clone/tree/image) does, and although it output some errors, the image seems to work.

- this forum post (https://www.raspberrypi.org/forums/viewtopic.php?t=191775#p1203116) contains a script to change PARTUUIDs on an image. I did not test this

**Comment by dolorosus** [comment]
I noticed the same issue, and created a pull request with a fix. As long as the request is pending  you may use the version from my repository.

**Comment by lzkelley** [comment]
The PR is merged, so I'm marking this as closed.  But if you still have any issues @kobbejager please let us know.
